### PR TITLE
Added StickySessions feature for process dipatching (tjanczuk/iisnode/pull/384)

### PR DESCRIPTION
**Pull request by JoHense**
Reopen this pull request in this more active fork of iisnode.
Plus a small fix based on https://github.com/tjanczuk/iisnode/pull/384#commitcomment-8683587

### CODE REVIEW

**Comment by ramijarrar** [comment]
@rramachand21 Any chance we can get this merged? Azure already provides stickiness at the server level and this would allow us to take advantage of all CPU cores on the larger instances.

**Comment by rramachand21** [comment]
This is included in https://github.com/Azure/iisnode/releases/tag/v0.2.24

**Comment by ramijarrar** [comment]
@rramachand21 That's awesome! We're super eager to try this out in production as soon as it's available in App Service.

**Comment by rramachand21** [comment]
Please note - do not use v0.2.24. Use v0.2.25.

**Pull request closed without merging**
